sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - src # build master branch only
install:
  - npm install -g hexo-cli
script:
  - cd blog
  - npm install
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $TOKEN
  keep-history: true
  on:
    branch: src
  local-dir: ./blog/public
  target_branch: master